### ISSUE TITLE
Stars update is broken

### ISSUE THREAD

**Issue by dizballanze** [k0kubun/github-ranking#21]
Hi,
seems that "Update stars" is broken. After clicking on this button the page starts to infinitely refresh, but stars aren't updating.

**Comment by k0kubun** [comment]
Thank you for reporting. I found my status update also failed and fixed it by changing database to allow utf8mb4 characters. Please notify me if your status update still fails.

**Comment by afc163** [comment]
https://gitstar-ranking.com/ant-design and https://gitstar-ranking.com/ant-design/ant-design are still failed
