### ISSUE TITLE
Update username

### ISSUE THREAD

**Issue by harshasrinivas** [k0kubun/github-ranking#4]
Github username, if changed, doesn't get updated.
Take this example of [my profile](http://githubranking.com/95harsha95).

**Comment by k0kubun** [comment]
Thank you for reporting an issue. I'll fix it.

**Comment by jasonleonhard** [comment]
Second. 

[my new username does not work](https://github-ranking.com/jasonleonhard)

[my old username](https://github-ranking.com/un5t0ppab13)

**Comment by hackjutsu** [comment]
Same here:

[my new username does not work](https://github-ranking.com/hackjutsu)

[my old username](https://github-ranking.com/registercosmo)

**Comment by ibrokemypie** [comment]
+1 2 years later

**Comment by k0kubun** [comment]
Sorry for letting you wait for a long time. I fixed to update username when you do "Update your stars". Please try it.

**Comment by k0kubun** [comment]
Ah... no, having bug, investigating now.

**Comment by k0kubun** [comment]
This is fixed.
